### ISSUE TITLE
您好，在rbft的cmd.go 文件中获取了RBFT_PRIVATE_KEY，并对其进行了编码操作，编码过程中通过fromHexChar函数对私钥进行16进制判断，而传统生成的公私密钥不是十六进制的，需要对原本生成的密钥进行16机制转换或其他的某些具体操作吗？该私钥是如何生成的

### ISSUE THREAD

**Issue by lbjwq** [yezhem/fabric-sample#2]

**Comment by lbjwq** [comment]
您好，传统生成的公私密钥不是十六进制的，代码中通过fromHexChar函数对私钥进行16进制判断，需要对原本生成的密钥进行16机制转换或其他的某些具体操作吗？

**Comment by DDlovei** [comment]
你好，我按照步骤修改无法运行，请问这个项目具体如何修改，有没有什么注意的细节？

**Comment by DDlovei** [comment]
我在 这一步上，出现了问题，在664行上。您知道如何解决嘛，
// orderer/common/server/main.go:664
consenters["pbft"] = pbft.New()

**Comment by lbjwq** [comment]
您好，我在664行未出现问题，你是在编译pbft还是rbft

**Comment by DDlovei** [comment]
![image](https://user-images.githubusercontent.com/62278864/133750598-1249c1e7-4f41-4580-93f4-b74d82f506ee.png)
我先使用go get go.dedis.ch/kyber把依赖下载到gopath下，然后用govendor add +e 将依赖导入到vendor中，但是在vendor下会有v3版本的报错,您知道是什么原因嘛
我的go版本是1.14.12  fabric版本是1.4.4

**Comment by lbjwq** [comment]
你的gopath和goroot设置好了吗，我的这些依赖是直接从github上下载后复制到相应的vendor文件夹下，未报错，你下载下来的依赖位置放对了吗

**Comment by DDlovei** [comment]
感谢您的回复。我的GOPATH是/opt/gopath   GOROOT是/usr/local/go   
fabric的路径是/opt/gopath/src/github.com/hyperledger/fabric
我觉得应该是kyber包的版本出了问题。请问您方便将go.dedis.ch文件打包发给我嘛，我查看一下kyber的版本。

**Comment by lbjwq** [comment]
你方便发下邮箱吗

**Comment by DDlovei** [comment]
741824564@qq.com
十分感谢您的帮助

**Comment by bingju** [comment]
> 我在 这一步上，出现了问题，在664行上。您知道如何解决嘛， // orderer/common/server/main.go:664 consenters["pbft"] = pbft.New()

我也遇到这问题了。如果你解决了，请819692697@qq.com

**Comment by yezhengmao1** [comment]
可以直接改下公钥和私钥生成方式，这只是一个 toy ， 最好可以从 file 读取，而非环境变量（环境变量用字符串仅是处理简单:-）。
