### ISSUE TITLE
请问这几个签名是怎么生成的，能否补充一下这几个值是怎么生成的

### ISSUE THREAD

**Issue by wangdongpei** [yezhem/fabric-sample#5]
* `PBFT_PUBLIC_KEY`：签名公钥
* `PBFT_PRIVATE_KEY`：签名私钥
* `PBFT_TBLS_PUBLIC_KEY`：门限签名公钥
* `PBFT_TBLS_PRIVATE_KEY`：门限签名私钥

**Comment by yezhengmao1** [comment]
可以参考 [cmd.go](https://github.com/yezhem/fabric-sample/blob/master/rbft/cmd/cmd.go) 文件，看下是怎么解析的，然后生成即可

**Comment by wangdongpei** [comment]
来信收到

**Comment by yezhengmao1** [comment]
crypto_test.go 文件里面也有，相关方法

**Comment by wangdongpei** [comment]
之前也在尝试自己写，不太懂kuber，写起来太痛苦了，感 谢，没想到会回复这么快，
